sudo: false
language: python
python:
  - 3.8
services:
  - postgresql
matrix:
  fast_finish: true
  include:
    - python: 3.8
      env: REQ="Django>=3.1,<3.2" DB=sqlite
    - python: 3.8
      env: REQ="Django>=3.1,<3.2" DB=postgres
    - python: 3.7
      env: REQ="Django>=3.1,<3.2" DB=sqlite
    - python: 3.6
      env: REQ="Django>=3.1,<3.2" DB=sqlite
    - python: 3.8
      env: REQ="Django>=3.0,<3.1" DB=sqlite
    - python: 3.7
      env: REQ="Django>=3.0,<3.1" DB=sqlite
    - python: 3.6
      env: REQ="Django>=3.0,<3.1" DB=sqlite
    - python: 3.7
      env: REQ="Django>=2.2,<3.0" DB=sqlite
    - python: 3.7
      env: REQ="Django>=2.2,<3.0" DB=postgres
    - python: 3.6
      env: REQ="Django>=2.2,<3.0" DB=sqlite
    - python: 3.5
      env: REQ="Django>=2.2,<3.0" DB=sqlite
    - python: 3.7
      env: REQ="Django>=2.1,<2.2" DB=sqlite
    - python: 3.7
      env: REQ="Django>=2.0,<2.1" DB=sqlite
    - python: 3.7
      env: REQ="Django>=1.11,<2.0" DB=sqlite
    - python: 3.6
      env: REQ="Django>=1.11,<2.0" DB=sqlite
    - python: 3.5
      env: REQ="Django>=1.11,<2.0" DB=sqlite
    - python: 2.7
      env: REQ="Django>=1.11,<2.0" DB=sqlite
install: 'pip install $REQ && pip install .'
script: make test SETTINGS=tests.travis_settings
before_script:
  - psql -c 'create database test_ool;' -U postgres
  - pip install psycopg2-binary
